# Generated by Django 3.0.4 on 2020-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('description', models.CharField(max_length=1240, verbose_name='Description')),
                ('category', models.CharField(max_length=240, verbose_name='Description')),
                ('task_status', models.BooleanField(default=True)),
                ('deadline', models.DateField(auto_now_add=True, verbose_name='Deadline Date')),
            ],
        ),
    ]
