# Generated by Django 3.0.4 on 2020-03-08 02:12

from django.db import migrations

def create_data(apps, schema_editor):
    Task = apps.get_model('to_do_list','Task')
    Task(name="Wash clothes",description="Wash clothes in the basement",category="chores",task_status=False,).save()

class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
